### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by QuiverlyRivalry** [BedrockCommunity/LobbyUtils#1]
Can u make useful plugin pls k thx bye

**Comment by NycuRO** [comment]
What's the problem with that?

**Comment by NycuRO** [comment]
What you want to create?

**Comment by NycuRO** [comment]
Tell me and i'm do.

**Comment by QuiverlyRivalry** [comment]
Well tbh no one needs this plugin, unless ur a network, maybe try something amazing like ik ur amazing coder blow our minds

**Comment by NycuRO** [comment]
Hmmm , gimme one exemple of your mids

**Comment by QuiverlyRivalry** [comment]
Make a new plugin, like no one has seen it. Maybe just a tip, a plugin which makes a UI, I’ll volunteer to help if you want

**Comment by NycuRO** [comment]
k

**Comment by NycuRO** [comment]
I don't need , but need ideea.

P.S. I don't post my shop thx or crate.
